// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/28/2025, 5:26:54 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/paymei/Documents/Development/github/blogger/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/paymei/Documents/Development/github/blogger/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/paymei/Documents/Development/github/blogger/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/paymei/Documents/Development/github/blogger/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/paymei/Documents/Development/github/blogger/plugins/**/*.{js,ts,mjs}","/Users/paymei/Documents/Development/github/blogger/composables/**/*.{js,ts,mjs}","/Users/paymei/Documents/Development/github/blogger/utils/**/*.{js,ts,mjs}","/Users/paymei/Documents/Development/github/blogger/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/paymei/Documents/Development/github/blogger/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/paymei/Documents/Development/github/blogger/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/paymei/Documents/Development/github/blogger/app.config.{js,ts,mjs}","/Users/paymei/Documents/Development/github/blogger/app/spa-loading-template.html"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;